# Generated by Django 4.2.13 on 2024-05-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristdestination',
            name='image',
        ),
    ]
