# Generated by Django 4.2.13 on 2024-06-08 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0002_remove_touristdestination_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristdestination',
            name='location_district',
        ),
        migrations.RemoveField(
            model_name='touristdestination',
            name='location_state',
        ),
        migrations.AddField(
            model_name='touristdestination',
            name='district',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristdestination',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='destination_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='touristdestination',
            name='state',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='touristdestination',
            name='weather',
            field=models.CharField(max_length=100),
        ),
    ]
