# Generated by Django 4.2.13 on 2024-06-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0003_remove_touristdestination_location_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='destination_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='TouristDestination',
        ),
    ]
