# Generated by Django 4.2.13 on 2024-06-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_app', '0004_destination_delete_touristdestination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='image',
        ),
    ]
